version: "3.9"
services:
  database:
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_USER: admin
      POSTGRES_DB: iot
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: christian.iwanzik@gmail.com
      PGADMIN_DEFAULT_PASSWORD: "s3cr3t"
    ports:
      - "8443:443"
      - "8081:80"

  iot:
    image: crud:latest
    environment:
      DB_CONNECTION: "jdbc:postgresql://database:5432/iot"
      DB_USERNAME: admin
      DB_PASSWORD: s3cr3t
    ports:
      - "8080:8080"