### INDEX PAGE
GET localhost:8080/

### CREATE THE HWR GROUP
POST localhost:8080/groups
Content-Type: application/json

{
  "name": "HWR",
  "description": "Hauswirtschaftsraum"
}

### GET A LIST OF GROUPS
GET localhost:8080/groups

### CREATE DEVICE Wetterstation1 FOR Hwr
POST localhost:8080/groups/HWR/devices
Content-Type: application/json

{
  "name": "Wetterstation1",
  "description": "",
  "type": "weather_station"
}

### GET ALL DEVICES GOR GROUP HWR
GET localhost:8080/groups/HWR/devices/Wetterstation1

### CREATE A NEW METRIC FOR Wetterstation1 in GROUP HWR
POST localhost:8080/groups/HWR/devices/Wetterstation1/metrics
Content-Type: application/json

{
  "unit": "°C",
  "value": 14.4,
  "timestamp": "2022-12-23T15:44:00+01:00"
}

### GET ALL METRIC FOR Wetterstation1 in GROUP HWR
GET localhost:8080/groups/HWR/devices/Wetterstation1/metrics

#### UPDATE A GROUP
#PUT localhost:8080/groups/HWR
#Content-Type: application/json
#
#{
#  "name": "hwr",
#  "description": "Neuer Raum. Mit Waschmaschine"
#}
#
#### DELETE A GROUP
#DELETE localhost:8080/groups/hwr